server:
  port: 8080
  servlet:
    context-path: /api/v1

tech-challenge:
  host: ${tech_challenge_host}

spring:
  application:
    name: tech-challenge
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    show-sql: false
    database-platform: ${JPA_DIALECT}
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

webhook:
  mercado-pago:
    access-token: ${ACCESS_TOKEN}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
  endpoints:
    web:
      exposure:
        include: health