apiVersion: v1
kind: Service
metadata:
  name: bd-lanchonete-service
  namespace: lanchonete-ns
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: bd-lanchonete