apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::327306512886:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS