apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
  namespace: lanchonete-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: lanchonete