apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanchonete-pv
  namespace: lanchonete-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"