apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-lanchonete-hpa
  namespace: lanchonete-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-lanchonete-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Target configurado para 75% de uso da CPU