name: ECR image build

on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: aws

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
        exclude: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Connecting to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t app-lanchonete:latest .
          docker tag app-lanchonete:latest 327306512886.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-3:latest
          docker push 327306512886.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-3:latest

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name fiap-tech-challenge-8soat-lanchonete-eks --region us-east-1

      - name: Test Kube Config
        run: |
          kubectl get nodes

      - name: Deploy Application
        run: |
          kubectl apply -f kubernetes/service-account.yaml --validate=false
          kubectl apply -f kubernetes/service.yaml --validate=false
          kubectl apply -f kubernetes/configmap.yaml --validate=false
          kubectl apply -f kubernetes/deployment.yaml --validate=false